POST http://localhost:3000/api/script
Content-Type: application/json

{
  "name": "asicfox",
  "script": "acixfox/script.js",
  "style": "acixfox/style.css",
  "lastDay": {
    "day": 29,
    "mount": 3,
    "year": 2021
  }
}